services:
  - type: web
    name: safe-scanner-api
    env: node
    plan: free
    buildCommand: npm install --prefix server
    startCommand: npm start --prefix server
    envVars:
      - key: MONGO_URI
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
